baseURL = 'https://yujunheo.me/'
languageCode = 'ko-kr'
title = 'Engineering Notes'
theme = "hugo-book"

[markup.goldmark.renderer]
  unsafe = true

[params]
  BookFavicon = 'favicon.png'
  BookLogo = 'original.png'